# Generated by Django 4.0.5 on 2022-06-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_portfolio_portfoliotable'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('desc', models.TextField()),
            ],
        ),
    ]
